#!/bin/bash

# Check if the script is running with sudo privileges
if [ "$EUID" -ne 0 ]; then
    echo "This script requires sudo privileges. Requesting sudo access..."

    # Request sudo access
    if sudo true; then
        echo "Sudo access granted."
    else
        echo "Sudo access request failed. Exiting."
        exit 1
    fi
fi

github_url="https://github.com/faithful1ofall/Auto-suite"
# Define the source file to be installed
source_file="faiv2"

# Clone the Git repository
echo "Cloning the repository..."
git clone -q "$github_url"

# Navigate into the cloned directory
cd Auto-suite

# Check out the desired branch
branch_name="shebangV.2.0.0"
git checkout -q "$branch_name"

# Define the target directory where you want to install the file (use a user-specific bin directory)
target_directory="$HOME/bin"

# Define the installed file name
installed_file="fai"

# Check if the source file exists
if [ -f "$source_file" ]; then
    # Check if the existing file in the target directory is named "fai"
    if [ -f "${target_directory}/${installed_file}" ]; then
        # Check if the existing file is the same as the source file
        if cmp -s "$source_file" "${target_directory}/${installed_file}"; then
            echo "No need to upgrade. File is identical."
        else
            echo "Replacing existing $installed_file" 
            rm "${target_directory}/${installed_file}"
            # Copy the source file to the target directory with the desired name
            echo "Installing as $installed_file"
            cp "$source_file" "${target_directory}/${installed_file}"
        fi
    else
        # Copy the source file to the target directory with the desired name
        echo "Installing as $installed_file"
        cp "$source_file" "${target_directory}/${installed_file}"
    fi

    # Make the installed file executable
    chmod +x "${target_directory}/${installed_file}"

    echo "Upgrade complete."
else
    echo "Error: The source file $source_file does not exist."
fi

# Clean up the cloned repository directory
cd ..
rm -rf Auto-suite
